# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 906)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(30, 10, 1101, 811))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 20, 1051, 221))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.DataCheckerListview = QtWidgets.QListView(self.groupBox_7)
        self.DataCheckerListview.setGeometry(QtCore.QRect(20, 50, 191, 151))
        self.DataCheckerListview.setObjectName("DataCheckerListview")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.browseButton = QtWidgets.QPushButton(self.groupBox_7)
        self.browseButton.setGeometry(QtCore.QRect(230, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.browseButton.setFont(font)
        self.browseButton.setObjectName("browseButton")
        self.cleanstatusLabel = QtWidgets.QLabel(self.groupBox_7)
        self.cleanstatusLabel.setGeometry(QtCore.QRect(330, 30, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cleanstatusLabel.setFont(font)
        self.cleanstatusLabel.setObjectName("cleanstatusLabel")
        self.checkButton = QtWidgets.QPushButton(self.groupBox_7)
        self.checkButton.setGeometry(QtCore.QRect(230, 90, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.checkButton.setFont(font)
        self.checkButton.setObjectName("checkButton")
        self.showStatus = QtWidgets.QTextEdit(self.groupBox_7)
        self.showStatus.setGeometry(QtCore.QRect(330, 50, 701, 151))
        self.showStatus.setAutoFillBackground(False)
        self.showStatus.setObjectName("showStatus")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 260, 1051, 511))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.correlationView = QtWidgets.QGraphicsView(self.groupBox_6)
        self.correlationView.setGeometry(QtCore.QRect(20, 50, 911, 441))
        self.correlationView.setObjectName("correlationView")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.corrButton = QtWidgets.QPushButton(self.groupBox_6)
        self.corrButton.setGeometry(QtCore.QRect(950, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.corrButton.setFont(font)
        self.corrButton.setObjectName("corrButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.picLabel = QtWidgets.QLabel(self.tab_2)
        self.picLabel.setGeometry(QtCore.QRect(200, 390, 691, 391))
        self.picLabel.setText("")
        self.picLabel.setObjectName("picLabel")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(30, 390, 187, 16))
        self.label_17.setObjectName("label_17")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(630, 20, 441, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.executeButton = QtWidgets.QPushButton(self.groupBox_9)
        self.executeButton.setGeometry(QtCore.QRect(320, 70, 101, 31))
        self.executeButton.setObjectName("executeButton")
        self.winlengthEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.winlengthEdit.setGeometry(QtCore.QRect(100, 40, 191, 21))
        self.winlengthEdit.setObjectName("winlengthEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox_9)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label_3.setObjectName("label_3")
        self.showStatus_npz = QtWidgets.QTextEdit(self.groupBox_9)
        self.showStatus_npz.setGeometry(QtCore.QRect(20, 140, 401, 191))
        self.showStatus_npz.setAutoFillBackground(False)
        self.showStatus_npz.setObjectName("showStatus_npz")
        self.processstatusLabel = QtWidgets.QLabel(self.groupBox_9)
        self.processstatusLabel.setGeometry(QtCore.QRect(20, 120, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.processstatusLabel.setFont(font)
        self.processstatusLabel.setObjectName("processstatusLabel")
        self.label_15 = QtWidgets.QLabel(self.groupBox_9)
        self.label_15.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label_15.setObjectName("label_15")
        self.winstepEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.winstepEdit.setGeometry(QtCore.QRect(100, 80, 191, 21))
        self.winstepEdit.setObjectName("winstepEdit")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 20, 591, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_19 = QtWidgets.QLabel(self.groupBox_10)
        self.label_19.setGeometry(QtCore.QRect(400, 30, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_16 = QtWidgets.QLabel(self.groupBox_10)
        self.label_16.setGeometry(QtCore.QRect(20, 30, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.InputSensorListview = QtWidgets.QListView(self.groupBox_10)
        self.InputSensorListview.setGeometry(QtCore.QRect(400, 50, 171, 121))
        self.InputSensorListview.setObjectName("InputSensorListview")
        self.inoutButton = QtWidgets.QPushButton(self.groupBox_10)
        self.inoutButton.setGeometry(QtCore.QRect(330, 250, 51, 31))
        self.inoutButton.setObjectName("inoutButton")
        self.label_21 = QtWidgets.QLabel(self.groupBox_10)
        self.label_21.setGeometry(QtCore.QRect(400, 190, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.senSelectButton = QtWidgets.QPushButton(self.groupBox_10)
        self.senSelectButton.setGeometry(QtCore.QRect(330, 90, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.senSelectButton.setFont(font)
        self.senSelectButton.setObjectName("senSelectButton")
        self.OutputSensorListview = QtWidgets.QListView(self.groupBox_10)
        self.OutputSensorListview.setGeometry(QtCore.QRect(400, 210, 171, 121))
        self.OutputSensorListview.setObjectName("OutputSensorListview")
        self.checkmodel = QtWidgets.QTableWidget(self.groupBox_10)
        self.checkmodel.setGeometry(QtCore.QRect(20, 50, 291, 281))
        self.checkmodel.setObjectName("checkmodel")
        self.checkmodel.setColumnCount(0)
        self.checkmodel.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.picLabel_2 = QtWidgets.QLabel(self.tab_3)
        self.picLabel_2.setGeometry(QtCore.QRect(200, 390, 691, 391))
        self.picLabel_2.setText("")
        self.picLabel_2.setObjectName("picLabel_2")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(30, 390, 187, 16))
        self.label_18.setObjectName("label_18")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 30, 421, 341))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox_8)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 64, 16))
        self.label_6.setObjectName("label_6")
        self.trainButton = QtWidgets.QPushButton(self.groupBox_8)
        self.trainButton.setGeometry(QtCore.QRect(310, 90, 101, 31))
        self.trainButton.setObjectName("trainButton")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_8)
        self.progressBar.setGeometry(QtCore.QRect(20, 280, 391, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.trainfreezeButton = QtWidgets.QPushButton(self.groupBox_8)
        self.trainfreezeButton.setGeometry(QtCore.QRect(310, 140, 101, 31))
        self.trainfreezeButton.setObjectName("trainfreezeButton")
        self.trainTimeLabel = QtWidgets.QLabel(self.groupBox_8)
        self.trainTimeLabel.setGeometry(QtCore.QRect(20, 310, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trainTimeLabel.setFont(font)
        self.trainTimeLabel.setObjectName("trainTimeLabel")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 21, 281, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.filterEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.filterEdit.setObjectName("filterEdit")
        self.gridLayout.addWidget(self.filterEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.numneuronEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.numneuronEdit.setObjectName("numneuronEdit")
        self.gridLayout.addWidget(self.numneuronEdit, 1, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 2, 0, 1, 1)
        self.batchszEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.batchszEdit.setObjectName("batchszEdit")
        self.gridLayout.addWidget(self.batchszEdit, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.epochEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.epochEdit.setObjectName("epochEdit")
        self.gridLayout.addWidget(self.epochEdit, 3, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 4, 0, 1, 1)
        self.outsensorEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.outsensorEdit.setObjectName("outsensorEdit")
        self.gridLayout.addWidget(self.outsensorEdit, 4, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 0, 1, 1)
        self.modelnameEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.modelnameEdit.setObjectName("modelnameEdit")
        self.gridLayout.addWidget(self.modelnameEdit, 5, 1, 1, 1)
        self.epochView = QtWidgets.QGraphicsView(self.tab_3)
        self.epochView.setGeometry(QtCore.QRect(470, 50, 601, 321))
        self.epochView.setObjectName("epochView")
        self.finalError_Label = QtWidgets.QLabel(self.tab_3)
        self.finalError_Label.setGeometry(QtCore.QRect(470, 30, 421, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.finalError_Label.setFont(font)
        self.finalError_Label.setObjectName("finalError_Label")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.testchooseButton = QtWidgets.QPushButton(self.tab_4)
        self.testchooseButton.setGeometry(QtCore.QRect(230, 40, 81, 31))
        self.testchooseButton.setObjectName("testchooseButton")
        self.signalView = QtWidgets.QGraphicsView(self.tab_4)
        self.signalView.setGeometry(QtCore.QRect(330, 300, 751, 221))
        self.signalView.setObjectName("signalView")
        self.TestDataListview = QtWidgets.QListView(self.tab_4)
        self.TestDataListview.setGeometry(QtCore.QRect(20, 40, 191, 231))
        self.TestDataListview.setObjectName("TestDataListview")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(20, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.predictLabel = QtWidgets.QLabel(self.tab_4)
        self.predictLabel.setGeometry(QtCore.QRect(330, 50, 391, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.predictLabel.setFont(font)
        self.predictLabel.setObjectName("predictLabel")
        self.predictButton = QtWidgets.QPushButton(self.tab_4)
        self.predictButton.setGeometry(QtCore.QRect(230, 340, 81, 31))
        self.predictButton.setObjectName("predictButton")
        self.ModelListview = QtWidgets.QListView(self.tab_4)
        self.ModelListview.setGeometry(QtCore.QRect(20, 300, 191, 111))
        self.ModelListview.setObjectName("ModelListview")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(20, 280, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.selmodelButton = QtWidgets.QPushButton(self.tab_4)
        self.selmodelButton.setGeometry(QtCore.QRect(230, 300, 81, 31))
        self.selmodelButton.setObjectName("selmodelButton")
        self.predstatusLabel = QtWidgets.QLabel(self.tab_4)
        self.predstatusLabel.setGeometry(QtCore.QRect(330, 20, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.predstatusLabel.setFont(font)
        self.predstatusLabel.setObjectName("predstatusLabel")
        self.residualView = QtWidgets.QGraphicsView(self.tab_4)
        self.residualView.setGeometry(QtCore.QRect(330, 530, 751, 221))
        self.residualView.setObjectName("residualView")
        self.totalsignalView = QtWidgets.QGraphicsView(self.tab_4)
        self.totalsignalView.setGeometry(QtCore.QRect(330, 70, 751, 221))
        self.totalsignalView.setObjectName("totalsignalView")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 20, 311, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_11)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 271, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 0, 1, 1)
        self.auto_winlengthEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.auto_winlengthEdit.setObjectName("auto_winlengthEdit")
        self.gridLayout_4.addWidget(self.auto_winlengthEdit, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 1, 0, 1, 1)
        self.auto_winstepEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.auto_winstepEdit.setObjectName("auto_winstepEdit")
        self.gridLayout_4.addWidget(self.auto_winstepEdit, 1, 1, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_12.setGeometry(QtCore.QRect(20, 160, 311, 231))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_12)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 27, 271, 181))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 0, 0, 1, 1)
        self.auto_filterEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.auto_filterEdit.setObjectName("auto_filterEdit")
        self.gridLayout_2.addWidget(self.auto_filterEdit, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 1, 0, 1, 1)
        self.auto_numneuronEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.auto_numneuronEdit.setObjectName("auto_numneuronEdit")
        self.gridLayout_2.addWidget(self.auto_numneuronEdit, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 2, 0, 1, 1)
        self.auto_epochEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.auto_epochEdit.setObjectName("auto_epochEdit")
        self.gridLayout_2.addWidget(self.auto_epochEdit, 2, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 3, 0, 1, 1)
        self.auto_batchszEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.auto_batchszEdit.setObjectName("auto_batchszEdit")
        self.gridLayout_2.addWidget(self.auto_batchszEdit, 3, 1, 1, 1)
        self.autoLabel = QtWidgets.QLabel(self.tab_6)
        self.autoLabel.setGeometry(QtCore.QRect(350, 20, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.autoLabel.setFont(font)
        self.autoLabel.setObjectName("autoLabel")
        self.showAutoStatus = QtWidgets.QTextEdit(self.tab_6)
        self.showAutoStatus.setGeometry(QtCore.QRect(350, 40, 731, 731))
        self.showAutoStatus.setAutoFillBackground(False)
        self.showAutoStatus.setObjectName("showAutoStatus")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 410, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.rbtn1 = QtWidgets.QRadioButton(self.groupBox_13)
        self.rbtn1.setGeometry(QtCore.QRect(20, 30, 83, 16))
        self.rbtn1.setObjectName("rbtn1")
        self.rbtn2 = QtWidgets.QRadioButton(self.groupBox_13)
        self.rbtn2.setGeometry(QtCore.QRect(20, 70, 151, 16))
        self.rbtn2.setObjectName("rbtn2")
        self.autoButton = QtWidgets.QPushButton(self.tab_6)
        self.autoButton.setGeometry(QtCore.QRect(120, 540, 101, 31))
        self.autoButton.setObjectName("autoButton")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(40, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tableView = QtWidgets.QTableView(self.tab_5)
        self.tableView.setGeometry(QtCore.QRect(40, 40, 881, 171))
        self.tableView.setObjectName("tableView")
        self.viewButton = QtWidgets.QPushButton(self.tab_5)
        self.viewButton.setGeometry(QtCore.QRect(940, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.viewButton.setFont(font)
        self.viewButton.setObjectName("viewButton")
        self.corrLabel_1 = QtWidgets.QLabel(self.tab_5)
        self.corrLabel_1.setGeometry(QtCore.QRect(931, 290, 31, 31))
        self.corrLabel_1.setText("")
        self.corrLabel_1.setObjectName("corrLabel_1")
        self.corrLabel_4 = QtWidgets.QLabel(self.tab_5)
        self.corrLabel_4.setGeometry(QtCore.QRect(931, 433, 31, 31))
        self.corrLabel_4.setText("")
        self.corrLabel_4.setObjectName("corrLabel_4")
        self.corrLabel_5 = QtWidgets.QLabel(self.tab_5)
        self.corrLabel_5.setGeometry(QtCore.QRect(931, 480, 31, 31))
        self.corrLabel_5.setText("")
        self.corrLabel_5.setObjectName("corrLabel_5")
        self.corrLabel_2 = QtWidgets.QLabel(self.tab_5)
        self.corrLabel_2.setGeometry(QtCore.QRect(931, 339, 31, 31))
        self.corrLabel_2.setText("")
        self.corrLabel_2.setObjectName("corrLabel_2")
        self.corrLabel_3 = QtWidgets.QLabel(self.tab_5)
        self.corrLabel_3.setGeometry(QtCore.QRect(931, 386, 31, 31))
        self.corrLabel_3.setText("")
        self.corrLabel_3.setObjectName("corrLabel_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(980, 280, 73, 241))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.SensorCheckerListview = QtWidgets.QListView(self.tab_5)
        self.SensorCheckerListview.setGeometry(QtCore.QRect(40, 240, 161, 281))
        self.SensorCheckerListview.setObjectName("SensorCheckerListview")
        self.tabWidget.addTab(self.tab_5, "")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(530, 840, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_7.setTitle(_translate("MainWindow", "檔案選取"))
        self.label_4.setText(_translate("MainWindow", "已匯入檔案"))
        self.browseButton.setText(_translate("MainWindow", "開啟檔案"))
        self.cleanstatusLabel.setText(_translate("MainWindow", "處理狀態"))
        self.checkButton.setText(_translate("MainWindow", "檢查數據"))
        self.groupBox_6.setTitle(_translate("MainWindow", "參數相關性分析"))
        self.label_8.setText(_translate("MainWindow", "相關性矩陣圖"))
        self.corrButton.setText(_translate("MainWindow", "分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "數據匯入"))
        self.label_17.setText(_translate("MainWindow", "輔助圖-CNN Model運算流程圖"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Input Matrix參數設定"))
        self.executeButton.setText(_translate("MainWindow", "格式轉檔"))
        self.label_3.setText(_translate("MainWindow", "資料流長度"))
        self.processstatusLabel.setText(_translate("MainWindow", "處理狀態"))
        self.label_15.setText(_translate("MainWindow", "滾動步幅"))
        self.groupBox_10.setTitle(_translate("MainWindow", "輸入輸出設定"))
        self.label_19.setText(_translate("MainWindow", "輸入感測器"))
        self.label_16.setText(_translate("MainWindow", "感測器確認"))
        self.inoutButton.setText(_translate("MainWindow", "=>"))
        self.label_21.setText(_translate("MainWindow", "輸出感測器"))
        self.senSelectButton.setText(_translate("MainWindow", "=>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "格式轉檔"))
        self.label_18.setText(_translate("MainWindow", "輔助圖-CNN Model運算流程圖"))
        self.groupBox_8.setTitle(_translate("MainWindow", "CNN Model參數設定"))
        self.label_6.setText(_translate("MainWindow", "訓練進度"))
        self.trainButton.setText(_translate("MainWindow", "模型訓練"))
        self.trainfreezeButton.setText(_translate("MainWindow", "暫停"))
        self.trainTimeLabel.setText(_translate("MainWindow", "訓練時間："))
        self.label_5.setText(_translate("MainWindow", "卷積層濾鏡數目"))
        self.label_2.setText(_translate("MainWindow", "單層神經元數目"))
        self.label_38.setText(_translate("MainWindow", "批次訓練數目"))
        self.label_9.setText(_translate("MainWindow", "訓練次數"))
        self.label_26.setText(_translate("MainWindow", "輸出感測器"))
        self.label_24.setText(_translate("MainWindow", "模型名稱"))
        self.finalError_Label.setText(_translate("MainWindow", "訓練成效圖 (訓練誤差：        、驗證誤差：        )"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "AI訓練"))
        self.testchooseButton.setText(_translate("MainWindow", "檔案選取"))
        self.label_22.setText(_translate("MainWindow", "已匯入檔案"))
        self.predictLabel.setText(_translate("MainWindow", "預測結果展示"))
        self.predictButton.setText(_translate("MainWindow", "模型預測"))
        self.label_25.setText(_translate("MainWindow", "已匯入模型"))
        self.selmodelButton.setText(_translate("MainWindow", "模型選擇"))
        self.predstatusLabel.setText(_translate("MainWindow", "處理狀態"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "準確度測試"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Input Matrix參數設定"))
        self.label_20.setText(_translate("MainWindow", "資料流長度"))
        self.label_23.setText(_translate("MainWindow", "滾動步幅"))
        self.groupBox_12.setTitle(_translate("MainWindow", "CNN Model參數設定"))
        self.label_34.setText(_translate("MainWindow", "卷積層濾鏡數目"))
        self.label_35.setText(_translate("MainWindow", "單層神經元數目"))
        self.label_36.setText(_translate("MainWindow", "訓練次數"))
        self.label_37.setText(_translate("MainWindow", "批次訓練數目"))
        self.autoLabel.setText(_translate("MainWindow", "處理狀態"))
        self.groupBox_13.setTitle(_translate("MainWindow", "輸入感測器選擇設定"))
        self.rbtn1.setText(_translate("MainWindow", "全部選擇"))
        self.rbtn2.setText(_translate("MainWindow", "依相關性係數選擇"))
        self.autoButton.setText(_translate("MainWindow", "自動訓練"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "自動訓練"))
        self.label_7.setText(_translate("MainWindow", "數據列表"))
        self.viewButton.setText(_translate("MainWindow", "數據波形檢視"))
        self.label_10.setText(_translate("MainWindow", "相關性100%"))
        self.label_11.setText(_translate("MainWindow", "相關性50%"))
        self.label_12.setText(_translate("MainWindow", "相關性0%"))
        self.label_13.setText(_translate("MainWindow", "相關性-50%"))
        self.label_14.setText(_translate("MainWindow", "相關性-100%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "測試頁"))
        self.closeButton.setText(_translate("MainWindow", "關閉"))

